Last login: Tue Jul  9 12:30:34 on ttys063
(base) CHARLES@MacBook-Pro-2 ~ % cd portfolio-management
(base) CHARLES@MacBook-Pro-2 portfolio-management % pyenv activate portfolio-management-env
(portfolio-management-env) (base) CHARLES@MacBook-Pro-2 portfolio-management % nano /Users/CHARLES/Portfolio-Management/.streamlit/secrets.toml


















  File: /Users/CHARLES/Portfolio-Management/.streamlit/secrets.toml   Modified  

api_key = "9MYRNNQDJ58W2U89"
another_secret = "uwe_098776"


















^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Pg   ^K Cut Text  ^C Cur Pos   
^X Exit      ^J Justify   ^W Where is  ^V Next Pg   ^U UnCut Text^T To Spell  
